jwt:
  secretpass: 'az20.77gez2023in'

auth:
  admin:
    register-code: 'teneke'

static:
  path:
    place-image: 'C:\Users\survi\OneDrive\Desktop\Projects\gezgin-backend\src\main\resources\static\place-images\'
    ads-image: 'C:\Users\survi\OneDrive\Desktop\Projects\gezgin-backend\src\main\resources\static\ads-images\'

server:
  port: 7090

spring:
  datasource:
    url: jdbc:mysql://containers-us-west-149.railway.app:7089/railway
    password: bXaAfr3377ugcPxL1J1R
    username: root
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.MySQLDialect
